# GitHubリポジトリのラベル定義
# このファイルはGitHub Actionsによって自動的に同期されます

- name: "バグ"
  color: "d73a4a"
  description: "バグレポート"

- name: "機能追加"
  color: "a2eeef"
  description: "新機能のリクエスト"

- name: "質問"
  color: "d876e3"
  description: "仕様や動作に関する質問"

- name: "一般"
  color: "0e8a16"
  description: "一般的な問題や提案"

- name: "ドキュメント"
  color: "0075ca"
  description: "ドキュメントの改善"

- name: "ヘルプ募集"
  color: "008672"
  description: "助けを求めています"

- name: "重複"
  color: "cfd3d7"
  description: "重複したissue"

- name: "無効"
  color: "e4e669"
  description: "無効なissue"

- name: "対応中"
  color: "fbca04"
  description: "現在対応中"

- name: "対応済み"
  color: "5319e7"
  description: "対応が完了しました"
